const KEY = "daily-accountability-v1";
const defaults = ["Make the bed", "Dishes / kitchen reset", "Pick up living room", "Laundry", "Take out trash", "30-minute walk", "Review spending"];
let data = load(); let selected = localDate(); let editingId = null;
const $ = (s) => document.querySelector(s);
function load() { try { return JSON.parse(localStorage.getItem(KEY)) || { templates: defaults.map(name => ({ id: crypto.randomUUID(), name })), days: {}, reminderTime:"20:00", reminderDismissed:"" }; } catch { return { templates: [], days: {}, reminderTime:"20:00", reminderDismissed:"" }; } }
function save() { localStorage.setItem(KEY, JSON.stringify(data)); }
function localDate() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function day(date=selected) { if (!data.days[date]) data.days[date] = { tasks: data.templates.map(t => ({ id: crypto.randomUUID(), templateId:t.id, name:t.name, startedAt:null, completedAt:null })), notes:"" }; return data.days[date]; }
function fmtTime(value) { return value ? new Date(value).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}) : "—"; }
function duration(task) { if (!task.startedAt) return "—"; const end = task.completedAt || new Date().toISOString(); let sec = Math.max(0, Math.round((new Date(end)-new Date(task.startedAt))/1000)); const h=Math.floor(sec/3600), m=Math.floor((sec%3600)/60); return h ? `${h}h ${m}m` : `${m}m`; }
function dateLabel(d=selected) { return new Date(`${d}T12:00:00`).toLocaleDateString([], {weekday:"long",month:"long",day:"numeric",year:"numeric"}); }
function render() { const d=day(), list=$("#task-list"); data.reminderTime ||= "20:00"; $("#date-picker").value=selected; $("#reminder-time").value=data.reminderTime; $("#day-notes").value=d.notes; list.innerHTML=""; const completed=d.tasks.filter(t=>t.completedAt).length; $("#day-summary").textContent=`${completed} of ${d.tasks.length} complete`;
 d.tasks.forEach(t => { const el=document.createElement("article"); el.className=`task ${t.completedAt?"done":""}`; const meta=t.completedAt ? `Completed ${fmtTime(t.completedAt)} · ${duration(t)}` : t.startedAt ? `<span class="active-dot"></span>Started ${fmtTime(t.startedAt)} · ${duration(t)} so far` : "Not started"; el.innerHTML=`<div class="task-main"><div class="task-name"></div><div class="task-meta">${meta}</div></div><div class="task-actions"></div>`; el.querySelector(".task-name").textContent=t.name; const a=el.querySelector(".task-actions"); if (!t.completedAt) { const start=button(t.startedAt?"Restart":"Start","small-button"); start.onclick=()=>{t.startedAt=new Date().toISOString();save();render();}; a.append(start); const complete=button("Complete","small-button primary"); complete.onclick=()=>{if(!t.startedAt)t.startedAt=new Date().toISOString();t.completedAt=new Date().toISOString();save();render();};a.append(complete); } else { const undo=button("Undo","small-button");undo.onclick=()=>{t.completedAt=null;save();render();};a.append(undo); } const edit=button("Edit","small-button");edit.onclick=()=>openTask(t);a.append(edit); const del=button("Delete","small-button delete");del.onclick=()=>{if(confirm(`Remove “${t.name}” from this day?`)){d.tasks=d.tasks.filter(x=>x.id!==t.id);save();render();}};a.append(del);list.append(el); }); $("#empty-state").hidden=!!d.tasks.length; save(); }
function button(label, cls="") { const b=document.createElement("button"); b.className=`button ${cls}`;b.textContent=label;return b; }
function openTask(task=null) { editingId=task?.id||null; $("#dialog-title").textContent=task?"Edit task":"Add task"; $("#task-name").value=task?.name||""; $("#task-recurring").checked=task?.templateId ? true : true; $("#task-dialog").showModal(); $("#task-name").focus(); }
function showReport() { const d=day(), done=d.tasks.filter(t=>t.completedAt), missed=d.tasks.length-done.length; $("#report-date").textContent=dateLabel(); $("#report-stats").innerHTML=`<div class="stat"><strong>${d.tasks.length ? Math.round(done.length/d.tasks.length*100) : 0}%</strong><span>completion rate</span></div><div class="stat"><strong>${done.length}</strong><span>completed</span></div><div class="stat"><strong>${missed}</strong><span>missed / unfinished</span></div>`; $("#report-rows").innerHTML=d.tasks.map(t=>`<tr><td></td><td class="${t.completedAt?"status-completed":"status-missed"}">${t.completedAt?"Completed":"Missed"}</td><td>${fmtTime(t.startedAt)}</td><td>${fmtTime(t.completedAt)}</td><td>${duration(t)}</td></tr>`).join(""); [...$("#report-rows").rows].forEach((row,i)=>row.cells[0].textContent=d.tasks[i].name); $("#report-notes-text").textContent=d.notes||"No notes recorded."; $("#report").hidden=false; }
$("#date-picker").onchange=e=>{selected=e.target.value;render();}; $("#reminder-time").onchange=e=>{data.reminderTime=e.target.value; data.reminderDismissed="";save();}; $("#add-task").onclick=()=>openTask(); $("#open-report").onclick=showReport; $("#end-day").onclick=showReport; $("#close-report").onclick=()=>$("#report").hidden=true; $("#dismiss-reminder").onclick=()=>{data.reminderDismissed=localDate();save();$("#report").hidden=true;}; $("#print-report").onclick=()=>window.print(); $("#day-notes").oninput=e=>{day().notes=e.target.value;save();};
$("#task-form").addEventListener("submit", e=>{ if(e.submitter?.value==="cancel") return; e.preventDefault(); const name=$("#task-name").value.trim();if(!name)return; const d=day(), recurring=$("#task-recurring").checked; if(editingId){const t=d.tasks.find(t=>t.id===editingId);t.name=name;if(recurring&&!t.templateId){const x={id:crypto.randomUUID(),name};data.templates.push(x);t.templateId=x.id;} } else { const t={id:crypto.randomUUID(),name,startedAt:null,completedAt:null}; if(recurring){const x={id:crypto.randomUUID(),name};data.templates.push(x);t.templateId=x.id;}d.tasks.push(t); } save();$("#task-dialog").close();render(); });
function checkReminder() { const now=new Date(), clock=`${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}`; if (selected===localDate() && clock>=data.reminderTime && data.reminderDismissed!==localDate() && $("#report").hidden) showReport(); }
render(); checkReminder(); setInterval(()=>{ if(day().tasks.some(t=>t.startedAt&&!t.completedAt)) render(); checkReminder(); },30000);
